export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FILTER_PRODUCTS_BY_NAME = 'FILTER_PRODUCTS_BY_NAME';
export const FILTER_PRODUCTS_BY_GROUP = 'FILTER_PRODUCTS_BY_GROUP';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';

export const FETCH_FEATURED_REQUEST = 'FETCH_FEATURED_REQUEST';
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
export const FETCH_FEATURED_FAILURE = 'FETCH_FEATURED_FAILURE';

export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_PRODUCT_COUNT = 'CART/INCREMENT_PRODUCT_COUNT';
export const DECREMENT_PRODUCT_COUNT = 'CART/DECREMENT_PRODUCT_COUNT';
export const DELETE_PRODUCT_FROM_CART = 'CART/DELETE_PRODUCT_FROM_CART';

export const FETCH_CHECKOUT_REQUEST = 'CART/FETCH_CHECKOUT_REQUEST';
export const FETCH_CHECKOUT_SUCCESS = 'CART/FETCH_CHECKOUT_SUCCESS';
export const FETCH_CHECKOUT_FAILURE = 'CART/FETCH_CHECKOUT_FAILURE';

export const CLEAR_SUCCESS = 'CART/CLEAR_SUCCESS';